name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      
      - name: 🛠️ Set Timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: 📦 Install Dependencies
        run: pnpm i

      - name: 🌌 Build Valaxy Blog
        run: pnpm run docs:build

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vuepress/dist
          force_orphan: true
          publish_branch: gh-pages